### ISSUE TITLE
Add Steam Controller support in this project

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4MapperTest#20]
At some point, Steam Controller support should be transferred from the SteamControllerTest project into this project. Both projects have an almost identical code base except for the Mapper base class and the DeviceEnumeration class. It would be nice to finally only have to manage one project to test changes after all this time; at one point, it was three projects as Switch Pro controller support was its own project.

**Comment by Ryochan7** [comment]
Got initial support finally included. Smoothing does not seem as aggressive for some reason compared to SteamControllerTest. I will try to look into why.

https://github.com/Ryochan7/DS4MapperTest/commit/76a2d8c6cea28d3a55ef05267fa4f89e9b7554a5

**Comment by Ryochan7** [comment]
The difference was that the TouchpadMouse action behaved slightly differently between the two projects. Changed a few bits to add low end throttling back in for Steam Controller usage. Now the mouse cursor behaves about the same for both projects.

https://github.com/Ryochan7/DS4MapperTest/commit/d0d645d4b33ef707475ba79e5d6cf145716cc26e

**Comment by Ryochan7** [comment]
Made some more changes. Pretty much got Steam Controller support on par with the existing SteamControllerTest project. Too bad I ended up bringing the changes over so late. I could technically consolidate what used to be 3 different mappers into 1 program now.

**Comment by Dont-Know-Nothing** [comment]
Hi Travis! Thanks for adding BLE support. everything seams to be working really good, (can't make mouse like Joystick on the gyro work, when joystick is set on the touchpad tough) Some minor glitches when modifying profiles (duplicated indexes) but they can be fixed by hand I think some mappings are not being deleted from the .json file when changes are made. Glitches aside, I'm going to use DS4MapperTest from now on. 
Please don't take it bad but.. I think you should be selling this, I'd gladly pay for something like DS4Windows with Steam Controller support.

**Comment by Ryochan7** [comment]
I fixed some issues with duplicate action indexes before but I guess there are still some left. When switching action types in the editor, the original action ID is supposed to be carried over. Ever since finding out using MSTest was feasible, I have thought about adding a small test suite to this project as well. It really helped clear up some profile problems with DS4Windows. Making some unit tests is something I should have done sooner but I had other tasks I wanted to do and I was paranoid that adding a second project to the solution would slow everything down.

I think at one time I wanted to allow multiple action types to be stored for an input group (like Steam Input) but I never implemented that; that is part of the reason the profile syntax is written the way it is. I do not think I ran into any ID problems with my most recent Daggerfall profile but I should look that profile over; not noticing any major problems except actions being written in order created rather than by ID.

I will take a look into the Mouse Joystick issue you mentioned. I have never made a profile where that action type is mapped to both the Touchpad and the Gyro. When using Mouse Joystick, I usually use Right Touchpad rather than Gyro.

I do not think trying to charge for this project or even DS4Windows would have ever been an option. Plenty of comments on the DSX Steam page show that most people only put up with DS4Windows, its quirks, and myself was because the program was free of cost; most people did not care that the program was open source and modifiable. Besides, like with other mapper programs (thinking Xpadder and reWASD mainly), people would likely just steal it if I would charge for it. Funny enough, other people could charge money for my code, lock features behind an upvote paywall (even after paying money), and be rewarded for it. I wanted to build a community around DS4Windows but that bombed miserably.

**Comment by Dont-Know-Nothing** [comment]
Sadly you are right about people stealing it if it had a cost and I guess few people like me want to have the option of using a Steam Controller without Steam. I never tried REWASD because of his business logic,, like you have said. Again, I would really like to try donate whatever I could, I think if you put some kind of Paypal link I will be able to make a donation.

I only use Mouse Like Joystick on the gyro and Joystick on the touchpad when I play games like RE4 and Resident Evil Revelations, where mixed gamepad and mouse doesn't work. I had issues with profiles before but now, with the error messages pointing to index issues, I was able to fix them editing manually the configuration files.

Sorry for my really bad English, I'm still trying to teach myself without using google translate and it's kind of hard to express myself sometimes (And hard to read for you)

**Comment by Dont-Know-Nothing** [comment]
I found a solution for my Mouse Like Joystick fetish, I just realized that I can map 2 (or more?) actions to a particular button so... I mapped the trigger as TrigerTranslate and LayerOps (Hold layer (1)). On that second layer, right touchpad as MouseLikeJoystick and gyro as MouseLikeJoystick.
