### ISSUE TITLE
Fix SC Dongle connection showing multiple controllers

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4MapperTest#29]
Got around to testing the Dongle connection since migrating the SteamControllerTest code over. I must have left something out because all 4 exposed interfaces show up in the app rather than only showing the interfaces with synced controllers. SteamControllerTest is still able to skip any interfaces with no controllers synced.

**Comment by Dont-Know-Nothing** [comment]
I knew the dongle supports up to 4 controller so I thought those 4 entries where there by design :) I've never seen them before because never used the dongle with SteamControllerTest or DS4MapperTest. 
Dongle is working OK in my end, I started using it because BLE is giving me ghost inputs and sometimes not responding to them. Don't know if it's me so I've tried different BT drivers without luck.. My other controller is working fine tough.

**Comment by Ryochan7** [comment]
Normally I do not use BLE mode for the Steam Controller because it has a lot slower response time (~16 ms on average) and less consistent connections compared to the Dongle. Also, most full input reports take 2 packets to be sent from the Steam Controller to get all the actual input data; the SC only uses 20 bytes for the input report when connected via BLE. Been using BLE while playing Red Faction and it works well enough for me except for Touchpad as Mouse. Gyro Mouse works fine though.

I did not carry over the BackendManager changes that take device sync state into account. Now everything seems to be working.

**Comment by Dont-Know-Nothing** [comment]
When I first got it, I played some games on steam over BLE without issues IIRC. I was just testing the BLE connection with the latest commits to check battery reading, don't know if it's fake but seems to be working. Different sets of batteries gives different readings. I been playing Silent Hill 3 these days over BLE and I get no input response or inputs that I didn't make at all (also tested with https://hardwaretester.com/gamepad) and same results. But hey can't complain, it's working really good with the dongle.
